### ISSUE TITLE
project config > All elements must have at least one site associated with them

### ISSUE THREAD

**Issue by rauwebieten** [verbb/navigation#241]
**Description**

When we deploy to our staging environment and apply the project config, we encounter following error:
   
    Applying changes from your project config files ... error: All elements must have at least one site associated with them.

Only way to temporarily fix this is deleting our current navigation nodes, and then deploy. 
Now the error does not happen.

In the change-log there is mentioned this issue is fixed, but I am still having this issue.

Kind regards
Peter

**Additional info**
- Plugin version: "verbb/navigation": "1.4.9"
- Craft version: "3.5.17.1"
- Multi-site: Yes 
- Propagate nodes: Yes

**Additional context**

Happens only when there are navigation nodes.

**Comment by rauwebieten** [comment]
Any news?

**Comment by engram-design** [comment]
I haven't been able to replicate this sorry. are you able to paste your navigation yaml file from `config/project/navigation/navs` for the corresponding navigation causing issues?

**Comment by rauwebieten** [comment]
```
handle: mainNavigation
instructions: ''
maxNodes: ''
name: 'Main navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
  verbb\navigation\nodetypes\SiteType:
    enabled: '1'
propagateNodes: false
siteSettings:
  2d5dcb20-4c52-4fcd-a381-aa936b719be3:
    enabled: '1'
  50e2d830-11c8-4932-b101-c6c222045dc2:
    enabled: '1'
  f7137bdf-6b7d-4248-a626-533202127616:
    enabled: '1'
sortOrder: 2
structure:
  maxLevels: null
  uid: 3cdf98f9-1e00-46dd-b45d-7ff4e73f3792
```
