### ISSUE TITLE
Navigation not enabled for site: default

### ISSUE THREAD

**Issue by knynkwl** [verbb/navigation#255]
**Description**
We recently updated:

Craft 3.4.24 -> 3.6.11
Navigation 1.3.20 -> 1.4.13

We are currently not able to access our old Navigation items, as it throws the error:
```
Page Not Found
Navigation not enabled for site: default
```

I noticed going through the yaml files, that all the navigations are missing some data.

Here is a navigation I created after the upgrade (works as intended):
```yaml
handle: aihaUniversitySidebarNavigation
instructions: ''
maxNodes: ''
name: 'AIHA University Sidebar Navigation'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: ''
  verbb\navigation\nodetypes\SiteType:
    enabled: ''
propagateNodes: false
siteSettings:
  49e3d086-5193-4125-b091-3e1532bd4730: # AIHA
    enabled: '1'
sortOrder: 96
structure:
  maxLevels: null
  uid: ff26d134-b622-4e2f-9a3e-e310f970c54e
```

Here is an example of the previous navigation items:
```yaml
handle: advertisingSponsorships
instructions: ''
name: Advertising/Sponsorships
propagateNodes: false
sortOrder: 12
structure:
  maxLevels: null
  uid: b2767e73-4198-4837-aa20-f64a8d857a02
```

Should I just fill in all the missing data, or maybe just `siteSettings`?

**Additional info**
- Plugin version: 1.4.13
- Craft version: 3.6.11
- Multi-site: Yes
- Propagate nodes: Yes
